domain_path: C:\Users\User\Documents\SSC\ProiectSSC\vitis\simdOpt\export\simdOpt\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
